// backend/constants/events.js
module.exports = {
  DENGUE_OUTBREAK_PREDICTED: 'DENGUE_OUTBREAK_PREDICTED',
  HOSPITAL_OVERLOAD_RISK: 'HOSPITAL_OVERLOAD_RISK',
  MEDICINE_SHORTAGE_RISK: 'MEDICINE_SHORTAGE_RISK',
};
